---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: talzzite
description: Personal bazzite image

base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    install:
      packages:
        - dnf-plugins-core
        - brave-browser
        - 1password
        - VK_hdr_layer
        - neovim

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.discordapp.Discord
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
